import * as XLSX from 'xlsx'
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

export const useExport = () => {
  const exportToExcel = (data: any[], fileName: string) => {
    const worksheet = XLSX.utils.json_to_sheet(data)
    const workbook = XLSX.utils.book_new()
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Sheet1')
    XLSX.writeFile(workbook, `${fileName}.xlsx`)
  }

  const exportToPDF = (data: any[], fileName: string, columns: string[]) => {
    const doc = new jsPDF({
      orientation: 'landscape',
      unit: 'mm',
      format: 'a4',
    })

    const title = fileName.replace(/_/g, ' ').toUpperCase()
    const date = new Date().toLocaleString()
    
    // Header styling
    doc.setFontSize(22)
    doc.setTextColor(30, 41, 59) // Slate 800
    doc.text(title, 14, 20)
    
    doc.setFontSize(10)
    doc.setTextColor(100, 116, 139) // Slate 500
    doc.text(`Generated by Nuxt Auto CRUD on ${date}`, 14, 28)

    const tableRows = data.map(item => columns.map(col => {
      const val = item[col]
      if (val === null || val === undefined) return ''
      return String(val)
    }))

    autoTable(doc, {
      startY: 35,
      head: [columns.map(col => col.toUpperCase())],
      body: tableRows,
      theme: 'grid',
      headStyles: { 
        fillColor: [51, 65, 85], // Slate 700
        textColor: [255, 255, 255], 
        fontStyle: 'bold', 
        lineWidth: 0.1,
        halign: 'left'
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252] // Slate 50
      },
      styles: { 
        fontSize: 9, 
        lineWidth: 0.1,
        cellPadding: 3,
        overflow: 'linebreak',
        textColor: [51, 65, 85], // Slate 700
        lineColor: [226, 232, 240] // Slate 200
      },
      margin: { top: 35, right: 14, bottom: 20, left: 14 },
      didDrawPage: (data) => {
        // Footer: Page X
        const pageSize = doc.internal.pageSize
        const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight()
        const pageWidth = pageSize.width ? pageSize.width : pageSize.getWidth()
        
        doc.setFontSize(10)
        doc.setTextColor(148, 163, 184) // Slate 400
        
        const str = 'Page ' + data.pageNumber
        doc.text(str, pageWidth - 30, pageHeight - 10)
        doc.text('Confidential - Internal Use Only', 14, pageHeight - 10)
      }
    })
    
    doc.save(`${fileName}_${new Date().getTime()}.pdf`)
  }

  return {
    exportToExcel,
    exportToPDF,
  }
}
